[book]
authors = ["Danny Rakita"]
language = "en"
src = "src"
title = "ad_trait: Automatic Differentiation for Rust"

[output.html]
git-repository-url = "https://github.com/djrakita/ad_trait"
edit-url-template = "https://github.com/djrakita/ad_trait/edit/main/docs/src/{path}"
